Counties:
  Alameda:
    Cities:
      - Alameda
      - Albany
      - Berkeley
      - Dublin
      - Emeryville
      - Fremont
      - Hayward
      - Livermore
      - Newark
      - Oakland
      - Piedmont
      - Pleasanton
      - San Leandro
      - Union City
  Butte:
    Cities:
      - Chico
  Contra Costa:
    Cities:
      - Antioch
      - Brentwood
      - Clayton
      - Concord
      - Danville
      - El Cerrito
      - Lafayette
      - Martinez
      - Oakley
      - Pittsburg
      - Pleasant Hill
      - Richmond
      - San Pablo
      - San Ramon
      - Walnut Creek
  El Dorado:
    Cities:
      - Placerville
      - South Lake Tahoe
  Fresno:
    Cities:
      - Clovis
      - Firebaugh
      - Fowler
      - Fresno
      - Huron
      - Kerman
      - Kingsburg
      - Orange Cove
      - Reedley
      - San Joaquin
      - Sanger
      - Selma
      - Coalinga
      - Mendota
      - Parlier
  Humboldt:
    Cities:
      - Arcata
      - Eureka
  Kern:
    Cities:
      - Kern
      - County
      - Arvin
      - Bakersfield
      - Ridgecrest
      - Shafter
      - Taft
      - Wasco
  Los Angeles:
    Cities:
      - Agoura Hills
      - Alhambra
      - Arcadia
      - Artesia
      - Avalon
      - Azusa
      - Baldwin Park
      - Bell
      - Bell Gardens
      - Bellflower
      - Beverly Hills
      - Bradbury
      - Burbank
      - Calabasas
      - Carson
      - Cerritos
      - Claremont
      - Commerce
      - Compton
      - Covina
      - Cudahy
      - Culver City
      - Diamond Bar
      - Downey
      - Duarte
      - El Monte
      - El Segundo
      - Gardena
      - Glendale
      - Glendora
      - Hawaiian Gardens
      - Hawthorne
      - Hermosa Beach
      - Hidden Hills
      - Huntington Park
      - Industry
      - Inglewood
      - Irwindale
      - La Canada-Flintridge
      - La Habra Heights
      - La Mirada
      - La Puente
      - La Verne
      - Lakewood
      - Lancaster
      - Lawndale
      - Lomita
      - Long Beach
      - Los Angeles
      - Lynwood
      - Malibu
      - Manhattan Beach
      - Monrovia
      - Montebello
      - Monterey Park
      - Norwalk
      - Palmdale
      - Palos Verdes Estates
      - Paramount
      - Pasadena
      - Pico Rivera
      - Pomona
      - Rancho Palos Verdes
      - Redondo Beach
      - Rolling Hills
      - Rolling Hills Estates
      - Rosemead
      - San Dimas
      - San Gabriel
      - San Fernando
      - San Marino
      - Santa Clarita
      - Santa Fe Springs
      - Santa Monica
      - Sierra Madre
      - Signal Hill
      - South El Monte
      - South Gate
      - South Pasadena
      - Temple City
      - Torrance
      - Walnut
      - West Covina
      - West Hollywood
      - Whittier
  Madera:
  Marin:
    Cities:
      - Belvedere
      - Corte Madera
      - Fairfax
      - Larkspur
      - Mill Valley
      - Novato
      - Ross
      - San Anselmo
      - San Rafael
      - Tiburon
  Mendocino:
    Cities:
      - Fort Bragg
  Merced:
  Monterey:
    Cities:
      - Carmel-by-the-Sea
      - Del Rey Oaks
      - Gonzales
      - Greenfield
      - King City
      - Marina
      - Monterey
      - Pacific Grove
      - Salinas
      - Sand City
      - Seaside
      - Soledad
  Napa:
    Cities:
      - American Canyon
      - Calistoga
      - Napa
      - St. Helena
      - Yountville
  Nevada:
    Cities:
      - Nevada City
  Orange:
    Cities:
      - Aliso Viejo
      - Anaheim
      - Brea
      - Fountain Valley
      - Laguna Beach
      - Newport Beach
      - San Clemente
      - Santa Ana
      - Westminster
  Riverside:
    Cities:
      - Beaumont
  Sacramento:
    Cities:
      - Citrus Heights
      - Elk Grove
      - Rancho Cordova
      - Galt
  San Bernardino:
    Cities:
      - Colton
  San Benito:
    Cities:
      - Hollister
      - San Juan Bautista
  San Diego:
    Cities:
      - Carlsbad
      - Chula Vista
      - Coronado
      - Del Mar
      - El Cajon
      - Encinitas
      - Escondido
      - La Mesa
      - Lemon Grove
      - National City
      - Oceanside
      - Poway
      - San Diego
      - San Marcos
      - Santee
      - Solana Beach
      - Vista
  San Francisco:
    Cities:
      - San Francisco
  San Joaquin:
    Cities:
      - Lodi
      - Manteca
      - Stockton
  San Luis Obispo:
    Cities:
      - Arroyo Grande
      - Atascadero
      - El Paso de Robles (Paso Robles)
      - Grover Beach
      - Morro Bay
      - San Luis Obispo
  San Mateo:
    Cities:
      - Atherton
      - Belmont
      - Brisbane
      - Burlingame
      - Colma
      - Daly City
      - East Palo Alto
      - Foster City
      - Half Moon Bay
      - Hillsborough
      - Menlo Park
      - Millbrae
      - Pacifica
      - Portola Valley
      - Redwood City
      - San Bruno
      - San Carlos
      - San Mateo
      - South San Francisco
      - Woodside
  Santa Clara:
    Cities:
      - Campbell
      - Cupertino
      - Gilroy
      - Los Altos
      - Los Altos Hills
      - Los Gatos
      - Milpitas
      - Monte Sereno
      - Morgan Hill
      - Mountain View
      - Palo Alto
      - San Jose
      - Santa Clara
      - Saratoga
      - Sunnyvale
  Santa Cruz:
    Cities:
      - Capitola
      - Santa Cruz
      - Scotts Valley
      - Watsonville
  Shasta:
    Cities:
      - Anderson
  Solano:
    Cities:
      - Benicia
      - Dixon
      - Fairfield
      - Suisun City
      - Vacaville
      - Vallejo
  Sonoma:
    Cities:
      - Cloverdale
      - Healdsburg
      - Petaluma
      - Rohnert Park
      - Sebastopol
      - Sonoma
      - Windsor
  Stanislaus:
    Cities:
      - Modesto
      - Turlock
      - Waterford
  Sutter:
    Cities:
      - Yuba City
  Tulare:
    Cities:
      - Porterville
      - Visalia
  Ventura:
    Cities:
      - Camarillo
      - Fillmore
      - Moorpark
      - Ojai
      - Oxnard
      - Port Hueneme
      - San Buenaventura (Ventura)
      - Santa Paula
      - Simi Valley
      - Thousand Oaks
  Yolo:
    Cities:
      - Davis
      - West Sacramento
      - Winters
      - Woodland
